version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: brigade
      POSTGRES_PASSWORD: brigade
    ports:
      - 5433:5432  
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080